#!/bin/bash
# CloudWatch Agent Lab - Start Here!

echo "╔═══════════════════════════════════════════════════════════════════╗"
echo "║                                                                   ║"
echo "║        CloudWatch Agent Installation Lab - START HERE             ║"
echo "║                                                                   ║"
echo "║        Installing the CloudWatch Agent on EC2 - Session 02        ║"
echo "║                                                                   ║"
echo "╚═══════════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 AVAILABLE DOCUMENTATION"
echo "═════════════════════════════════════════════════════════════════════"
echo ""
echo "1️⃣  MANIFEST.sh (THIS FILE)"
echo "   └─ Lab overview and deliverables summary"
echo ""
echo "2️⃣  QUICK-START.md"
echo "   └─ 4-step quick guide for getting running in 2 minutes"
echo "   └─ 5 different setup options"
echo "   └─ Recommended: Start here!"
echo ""
echo "3️⃣  README.md"
echo "   └─ Complete 500+ line reference documentation"
echo "   └─ Prerequisites, installation methods, configuration"
echo "   └─ Comprehensive troubleshooting guide"
echo ""
echo "4️⃣  COMMAND-REFERENCE.md"
echo "   └─ All commands organized by category"
echo "   └─ Copy-paste ready for quick reference"
echo ""
echo "5️⃣  FILE-INDEX.md"
echo "   └─ Complete file catalog and navigation guide"
echo "   └─ Use cases and file dependencies"
echo ""
echo "═════════════════════════════════════════════════════════════════════"
echo ""
echo "🚀 QUICK START OPTIONS"
echo "═════════════════════════════════════════════════════════════════════"
echo ""
echo "OPTION 1: Fastest (2 minutes)"
echo "─────────────────────────────────────"
echo "  \$ sudo bash quick-start.sh cloudwatch-config.json"
echo ""
echo "OPTION 2: Manual Learning (15 minutes)"
echo "─────────────────────────────────────"
echo "  \$ cat QUICK-START.md"
echo "  \$ sudo bash install-cloudwatch-agent.sh"
echo "  \$ sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-config-wizard"
echo "  \$ sudo bash manage-agent.sh start"
echo "  \$ sudo bash verify-agent.sh"
echo ""
echo "OPTION 3: Infrastructure as Code"
echo "─────────────────────────────────────"
echo "  \$ aws cloudformation create-stack \\"
echo "      --stack-name cloudwatch-lab \\"
echo "      --template-body file://cloudformation-template.yaml \\"
echo "      --parameters ParameterKey=KeyName,ParameterValue=my-key \\"
echo "      --capabilities CAPABILITY_NAMED_IAM"
echo ""
echo "═════════════════════════════════════════════════════════════════════"
echo ""
echo "✅ PREREQUISITES"
echo "═════════════════════════════════════════════════════════════════════"
echo ""
echo "REQUIRED:"
echo "  ✓ EC2 instance (Amazon Linux 2, RHEL, CentOS, Ubuntu, Debian)"
echo "  ✓ SSH access"
echo "  ✓ sudo/root access"
echo ""
echo "CRITICAL - IAM ROLE WITH CLOUDWATCH PERMISSIONS:"
echo "  ✓ EC2 instance must have IAM role attached"
echo "  ✓ Role must have CloudWatchAgentServerPolicy"
echo ""
echo "Quick setup:"
echo "  aws iam attach-role-policy \\"
echo "    --role-name YourEC2Role \\"
echo "    --policy-arn arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"
echo ""
echo "Verify:"
echo "  curl http://169.254.169.254/latest/meta-data/iam/security-credentials/"
echo "  (Should return role name)"
echo ""
echo "═════════════════════════════════════════════════════════════════════"
echo ""
echo "📁 FILE STRUCTURE"
echo "═════════════════════════════════════════════════════════════════════"
echo ""
echo "📖 Documentation (4 files)"
echo "  ├─ QUICK-START.md ..................... Start here! (5 min)"
echo "  ├─ README.md .......................... Complete reference (20 min)"
echo "  ├─ COMMAND-REFERENCE.md .............. Command cheat sheet"
echo "  └─ FILE-INDEX.md ..................... File catalog"
echo ""
echo "🔧 Installation & Setup (3 files)"
echo "  ├─ quick-start.sh .................... One-command automation"
echo "  ├─ install-cloudwatch-agent.sh ....... Install only"
echo "  └─ user-data.sh ...................... EC2 launch auto-setup"
echo ""
echo "⚙️ Configuration & Policies (2 files)"
echo "  ├─ cloudwatch-config.json ............ Pre-built agent config"
echo "  └─ iam-policy.json ................... IAM permissions"
echo ""
echo "🛠️ Management & Utilities (3 files)"
echo "  ├─ manage-agent.sh ................... Agent control (12 commands)"
echo "  ├─ verify-agent.sh ................... Health check (10 checks)"
echo "  └─ deploy-bulk.sh .................... Multi-instance deployment"
echo ""
echo "📦 Infrastructure as Code (1 file)"
echo "  └─ cloudformation-template.yaml ...... Full stack automation"
echo ""
echo "═════════════════════════════════════════════════════════════════════"
echo ""
echo "⚡ QUICK COMMANDS"
echo "═════════════════════════════════════════════════════════════════════"
echo ""
echo "Setup:"
echo "  sudo bash quick-start.sh cloudwatch-config.json"
echo ""
echo "Service:"
echo "  sudo systemctl status amazon-cloudwatch-agent"
echo "  sudo bash manage-agent.sh health"
echo ""
echo "Verify:"
echo "  sudo bash verify-agent.sh"
echo "  sudo tail -f /opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log"
echo ""
echo "CloudWatch:"
echo "  aws cloudwatch list-metrics --namespace \"CustomApplication\""
echo "  aws logs tail /aws/ec2/system-logs --follow"
echo ""
echo "═════════════════════════════════════════════════════════════════════"
echo ""
echo "✓ SUCCESS CRITERIA"
echo "═════════════════════════════════════════════════════════════════════"
echo ""
echo "Lab is complete when:"
echo "  ✓ Agent binary installed"
echo "  ✓ Configuration deployed"
echo "  ✓ Service running (systemctl status)"
echo "  ✓ Metrics in CloudWatch (2-3 min latency)"
echo "  ✓ Logs in CloudWatch Logs"
echo "  ✓ Health check passing"
echo ""
echo "═════════════════════════════════════════════════════════════════════"
echo ""
echo "📚 WHERE TO START"
echo "═════════════════════════════════════════════════════════════════════"
echo ""
echo "New to CloudWatch Agent?"
echo "  1. Read: QUICK-START.md (5 minutes)"
echo "  2. Run: sudo bash quick-start.sh cloudwatch-config.json"
echo "  3. Verify: sudo bash verify-agent.sh"
echo ""
echo "Need detailed reference?"
echo "  └─ Read: README.md"
echo ""
echo "Need a specific command?"
echo "  └─ Check: COMMAND-REFERENCE.md"
echo ""
echo "Need all file information?"
echo "  └─ See: FILE-INDEX.md"
echo ""
echo "═════════════════════════════════════════════════════════════════════"
echo ""
echo "🎓 LEARNING PATH"
echo "═════════════════════════════════════════════════════════════════════"
echo ""
echo "1. Understand the 4 steps"
echo "   └─ Read: QUICK-START.md (First section)"
echo ""
echo "2. Review prerequisites"
echo "   └─ Read: QUICK-START.md (Prerequisites section)"
echo ""
echo "3. Choose your setup path"
echo "   └─ Quick: sudo bash quick-start.sh"
echo "   └─ Manual: Follow QUICK-START.md path 2"
echo "   └─ IaC: Use cloudformation-template.yaml"
echo ""
echo "4. Monitor setup"
echo "   └─ Read: CloudWatch Console"
echo "   └─ Check: CloudWatch Metrics"
echo "   └─ Verify: CloudWatch Logs"
echo ""
echo "5. Master operations"
echo "   └─ Use: manage-agent.sh"
echo "   └─ Reference: COMMAND-REFERENCE.md"
echo ""
echo "═════════════════════════════════════════════════════════════════════"
echo ""
echo "✨ Ready to start? Run:"
echo ""
echo "    cat QUICK-START.md"
echo ""
echo "═════════════════════════════════════════════════════════════════════"
echo ""
